extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.cp]
pipeline = [
    "bril2json",
    "python3 constant_propagation.py",
    "brili -p {args}",
]